# Hyperparameter Tuning with GridSearchCV


 In almost any Machine Learning project, we train different models on the dataset and select the one with the best performance. However, there is room for improvement as we cannot say for sure that this particular model is best for the problem at hand. Hence, our aim is to improve the model in any way possible. One important factor in the performances of these models are their hyperparameters, once we set appropriate values for these hyperparameters, the performance of a model can improve significantly. In this Notebook, we will find out how we can find optimal values for the hyperparameters of a model by using GridSearchCV.

# What is GridSearchCV?
First, let us understand what is grid search? It is the process of performing hyperparameter tuning in order to determine the optimal values for a given model. As mentioned above, the performance of a model significantly depends on the value of hyperparameters. Note that there is no way to know in advance the best values for hyperparameters so ideally, we need to try all possible values to know the optimal values. Doing this manually could take a considerable amount of time and resources and thus we use GridSearchCV to automate the tuning of hyperparameters.

GridSearchCV is a function that comes in Scikit-learn’s(or SK-learn) model_selection package.So an important point here to note is that we need to have Scikit-learn library installed on the computer. This function helps to loop through predefined hyperparameters and fit your estimator (model) on your training set. So, in the end, we can select the best parameters from the listed hyperparameter

In [2]:
# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

# Importing the dataset
dataset = pd.read_csv('Advertising_data.csv')

In [3]:
dataset.head()

User ID  Gender   Age  EstimatedSalary  Purchased
0  15624510    Male  19.0          19000.0          0
1  15810944    Male  35.0          20000.0          0
2  15668575  Female  26.0          43000.0          0
3  15603246  Female  27.0          57000.0          0
4  15804002    Male  19.0          76000.0          0

In [4]:
dataset = pd.get_dummies(dataset)

In [5]:
dataset.head()

User ID   Age  EstimatedSalary  Purchased  Gender_Female  Gender_Male
0  15624510  19.0          19000.0          0              0            1
1  15810944  35.0          20000.0          0              0            1
2  15668575  26.0          43000.0          0              1            0
3  15603246  27.0          57000.0          0              1            0
4  15804002  19.0          76000.0          0              0            1

In [6]:
dataset.drop('User ID' , axis=1 , inplace=True)

In [7]:
X = dataset.drop('Purchased' , axis = 1)
y = dataset.Purchased

In [8]:
X

Age  EstimatedSalary  Gender_Female  Gender_Male
0    19.0          19000.0              0            1
1    35.0          20000.0              0            1
2    26.0          43000.0              1            0
3    27.0          57000.0              1            0
4    19.0          76000.0              0            1
..    ...              ...            ...          ...
395  46.0          41000.0              1            0
396  51.0          23000.0              0            1
397  50.0          20000.0              1            0
398  36.0          33000.0              0            1
399  49.0          36000.0              1            0

[400 rows x 4 columns]

In [9]:
y

0      0
1      0
2      0
3      0
4      0
      ..
395    1
396    1
397    1
398    0
399    1
Name: Purchased, Length: 400, dtype: int64

In [22]:
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.preprocessing import StandardScaler

In [17]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 5)

In [18]:
X_train.shape

(300, 4)

In [19]:
y_test.shape

(100,)

In [20]:
y_train.shape

(300,)

In [21]:
X_test.shape

(100, 4)

In [25]:
# Feature Scaling
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.fit_transform(X_test)

In [26]:
X_test

array([[ 0.87960747,  0.69869621,  1.02020406, -1.02020406],
       [-1.6768405 , -1.29513724,  1.02020406, -1.02020406],
       [-0.06722511, -0.55457053, -0.98019606,  0.98019606],
       [-1.20342421, -1.12423723,  1.02020406, -1.02020406],
       [ 0.21682466,  0.15751284, -0.98019606,  0.98019606],
       [ 0.02745814, -0.0418705 , -0.98019606,  0.98019606],
       [-0.25659163, -0.81092055, -0.98019606,  0.98019606],
       [ 0.50087444,  0.10054617,  1.02020406, -1.02020406],
       [-0.16190837, -0.5260872 , -0.98019606,  0.98019606],
       [ 0.50087444,  0.21447951,  1.02020406, -1.02020406],
       [-0.06722511,  1.52471293, -0.98019606,  0.98019606],
       [-1.10874095,  0.5277962 , -0.98019606,  0.98019606],
       [-0.73000792,  0.32841285,  1.02020406, -1.02020406],
       [-0.5406414 , -0.15580384, -0.98019606,  0.98019606],
       [-0.16190837, -0.69698721,  1.02020406, -1.02020406],
       [-1.6768405 , -1.32362058, -0.98019606,  0.98019606],
       [-0.16190837,  2.

In [27]:
X_train

array([[ 0.77063564, -1.37090753, -1.03390789,  1.03390789],
       [-0.95681661, -0.74731782,  0.96720415, -0.96720415],
       [ 1.25048349, -1.37090753, -1.03390789,  1.03390789],
       ...,
       [-0.95681661, -1.1036548 , -1.03390789,  1.03390789],
       [ 1.63436177,  1.8064305 ,  0.96720415, -0.96720415],
       [ 2.11420962, -1.0442653 , -1.03390789,  1.03390789]])

In [28]:
# Fitting SVM to the Training set
svm = SVC(kernel = 'rbf', random_state = 0)
svm.fit(X_train, y_train)

SVC(random_state=0)

In [53]:
svm.support_

array([ 10,  16,  27,  37,  38,  47,  53,  60,  73,  74,  79,  91,  95,
        97,  98, 122, 124, 128, 134, 136, 137, 154, 155, 158, 163, 165,
       167, 168, 179, 180, 187, 196, 198, 206, 209, 216, 217, 220, 222,
       226, 227, 238, 242, 245, 255, 266, 267, 275, 281, 282, 293, 295,
         0,   3,  13,  23,  25,  32,  33,  49,  61,  65,  68,  71,  77,
        83, 103, 113, 117, 119, 125, 129, 133, 139, 141, 146, 151, 152,
       156, 169, 177, 181, 188, 195, 201, 214, 215, 219, 221, 223, 228,
       229, 230, 234, 236, 240, 243, 247, 250, 271, 273, 274, 276, 284])

In [29]:
y_pred = svm.predict(X_test)

In [30]:
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)

In [37]:
cm

array([[61,  5],
       [ 2, 32]], dtype=int64)

In [35]:
y_pred

array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0,
       1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1,
       0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1], dtype=int64)

In [36]:
y_test

218    0
191    0
117    0
50     0
348    0
      ..
368    0
89     0
182    1
219    1
18     1
Name: Purchased, Length: 100, dtype: int64

In [39]:
from sklearn.metrics import accuracy_score
acc = accuracy_score(y_test,y_pred)
acc

0.93

In [45]:
# Applying Grid Search to find the best model and the best parameters
parameters = [{'C':[1,3,5,6,7,8,9,10,15,20,25,30,33,35] , 'kernel' : ['Linear' ]} , 
             {'C':[1,3,5,6,7,8,9,10,15,20,25,30,33,35] , 'kernel' : ['rbf'] ,
              'gamma': [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9]}] 
grid_search  = GridSearchCV(estimator=svm , param_grid=parameters)
grid_search = grid_search.fit(X_train ,y_train)

C:\Users\96654\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:372: FitFailedWarning: 
70 fits failed out of a total of 700.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
70 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\96654\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py", line 680, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\96654\anaconda3\lib\site-packages\sklearn\svm\_base.py", line 255, in fit
    fit(X, y, sample_weight, solver_type, kernel, random_seed=seed)
  File "C:\Users\96654\anaconda3\lib\site-packages\sklearn\svm\_base.py", line 315, in _dense_fit
    ) = libsvm.fit(
  File "sklearn\svm\_libsvm.pyx"

In [46]:
grid_search.best_params_

{'C': 3, 'gamma': 0.8, 'kernel': 'rbf'}

In [47]:
grid_search.best_score_

0.9133333333333333

In [57]:
classifier = SVC(C= 3, gamma= 0.8, kernel= 'rbf')
classifier.fit(X_train, y_train)

SVC(C=3, gamma=0.8)

In [58]:
y_predict = classifier.predict(X_test)

In [59]:
# Making the Confusion Matrix
confusion_matrix = confusion_matrix(y_test, y_predict)

In [60]:
confusion_matrix

array([[61,  5],
       [ 3, 31]], dtype=int64)

In [61]:
accuracy_score(y_predict , y_test)

0.92